version: "3"
services:
  app:
    container_name: "be_config"
    build: .
    ports:
      - 8888:8888
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./config.jar:/usr/src/app/config.jar
      - ./bootstrap.yml:/usr/src/app/bootstrap.yml
      - ./logs:/usr/src/app/logs/
