server.port: 8090

spring:
  application:
    name: admin
  boot:
    admin:
      discovery:
        ignored-services: admin
      notify:
        discord:
          webhook-url: https://discordapp.com/api/webhooks/758643508818083860/_S4f5pX2jBZueWeSEZLWmomATCvRCHhhzU98jpuqdWFdy41ngRNzNcFOKPOK9XBt4m7e

fanatic:
  user:
    name: admin
    password: admin

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true