server:
  port: 9000

spring:
  application:
    name: fanaman
  datasource:
    url: jdbc:postgresql://192.168.210.201:5432/PRODUCT_CONTROL
    username: postgres
    password: Fanatic01

## Configuring info endpoint
info.app.name: Fanaman System # Project's Config
info.app.description: Fanamanスシステム # Project's Configroject's Config

fanatic:
  application.name.jp: Fanaman
  fanaman:
    user:
      username: admin
      password: Fanatic01
    allowed-ip-addresses: 192.168.210.201

