version: "3"
services:
  static-web:
    container_name: $FE_CONTAINER_NAME
    build: .
    ports:
      - $FE_SYSTEM_PORT:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./dist/$FE_SYSTEM_NAME/:/usr/share/nginx/html
