version: "3"
services:
  static-web:
    container_name: "fe_menu"
    build: .
    ports:
      - 4299:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./dist/Fanatic-Menu/:/usr/share/nginx/html
