version: "3"
services:
  app:
    container_name: "be_gateway"
    build: .
    ports:
      - 8080:8080
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./gateway.jar:/usr/src/app/gateway.jar
      - ./bootstrap.yml:/usr/src/app/bootstrap.yml
      - ./logs:/usr/src/app/logs/
