version: "3"
services:
  app:
    container_name: "be_gateway"
    build: .
    ports:
      - 8080:8080
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - .:/usr/src/app
