version: '3'

services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "18080:8080"
      - "50000:50000"
    restart: unless-stopped
volumes:
  jenkins_home:
