version: "3"
services:
  app:
    container_name: "be_discover"
    build: .
    ports:
      - 8889:8889
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - .:/usr/src/app
