version: "3"
services:
  app:
    container_name: "be_discover"
    build: .
    ports:
      - 8889:8889
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./discovery.jar:/usr/src/app/discovery.jar
      - ./application.yml:/usr/src/app/application.yml
      - ./logs:/usr/src/app/logs/
