version: "3"
services:
  app:
    container_name: "be_fanaman"
    build: .
    ports:
      - 8090:8090
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./fanaman.jar:/usr/src/app/fanaman.jar
      - ./bootstrap.yml:/usr/src/app/bootstrap.yml
      - ./logs:/usr/src/app/logs/
